name: e2e
on: [deployment_status]

jobs:
  visual-tests:
    name: "basic visual comparison tests"
    timeout-minutes: 5
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.31.2-focal
    steps:
      - uses: actions/checkout@v3
      
      - run: corepack enable
          
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - run:
          echo ${{github.event}};
          echo ${{context.issue.number}};
          echo ${{github.context.issue.number}};

      - name: Install dependencies
        run: pnpm install --ignore-scripts
      
      - name: Get Vercel's Alias Preview URL
        id: alias-preview-url
        uses: justincase-jp/vercel-preview-url-alias@0.2.1
        with:
          vercel_access_token: ${{ secrets.VERCEL_ACCESS_TOKEN }}
          vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID }}
          fail_when_cancelled: false

      - name: Find Comment for updating snapshots
        if: |
          github.ref != 'refs/heads/main' &&
          steps.alias-preview-url.outputs.status == 'READY'
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.context.payload.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: '### Check the checkbox to automatically update all changed snapshots'

      - name: Comment
        if: |
          github.ref != 'refs/heads/main' &&
          steps.alias-preview-url.outputs.status == 'READY'
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.context.payload.pull_request.number }}
          edit-mode: replace
          body: |
            ### Check the checkbox to automatically update all changed snapshots
            - [ ] Update All Snapshots

      - name: Tests
        if: steps.alias-preview-url.outputs.status == 'READY'
        run: HOME=/root pnpm e2e
        env:
          BASE_URL: https://${{ steps.alias-preview-url.outputs.preview_url_origin }}

      - name: Upload HTML report as artifact.
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: visual-tests
          path: playwright-report
