name: snapshot

on:
  issue_comment:
    types: [edited]

jobs:
  update-snapshots:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body,  '- [x] Update All Snapshots') }}
    container: mcr.microsoft.com/playwright:v1.33.0-focal
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
          ref: ${{ github.head_ref }}

      - name: Get target branch's head commit info
        id: target-pull-request
        uses: actions/github-script@v7
        with:
          script: |
            const head = (await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            })).data.head;
            core.setOutput('ref', head.ref);
            core.setOutput('sha', head.sha);

      - name: Get Vercel's Alias Preview URL
        id: alias-preview-url
        uses: justincase-jp/vercel-preview-url-alias@0.3.0
        with:
          vercel_access_token: ${{ secrets.VERCEL_ACCESS_TOKEN }}
          vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID }}
          fail_when_cancelled: true
          commit_sha: ${{ steps.target-pull-request.outputs.sha }}

      - name: Checkout target branch
        if: steps.alias-preview-url.outputs.status == 'READY'
        run:
          git config --global --add safe.directory /__w/next-startbootstrap-agency/next-startbootstrap-agency;
          git fetch;
          git checkout ${{ steps.target-pull-request.outputs.ref }};

      - if: steps.alias-preview-url.outputs.status == 'READY'
        run: corepack enable
          
      - uses: actions/setup-node@v4
        if: steps.alias-preview-url.outputs.status == 'READY'
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies
        if: steps.alias-preview-url.outputs.status == 'READY'
        run: pnpm install --ignore-scripts
      
      - name: Update Snapshots
        if: steps.alias-preview-url.outputs.status == 'READY'
        run: HOME=/root pnpm e2e:upd
        env:
          BASE_URL: https://${{ steps.alias-preview-url.outputs.preview_url_origin }}

      - uses: stefanzweifel/git-auto-commit-action@v5
        if: steps.alias-preview-url.outputs.status == 'READY'
        with:
          commit_message: 'chore: update changed snapshots'
